port: "8080"

log:
  level: info

mongodb:
  uri: "mongodb://localhost:27017"
  database: "petProjectMongoDB"

redis:
  uri: "localhost:6379"

salt: "maklaud57"
secretKey: "JeksyJohns"
signingKay: "123123"